### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by Arjunsankarlal** [thunlp/OpenQA#7]
After doing all the setup, While running with the command given in the readme I am getting this issue.

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 816, in <module>
    main(args)
  File "main.py", line 611, in main
    PROCESS_TOK = tok_class(**tok_opts)
  File "/OpenQA/src/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/OpenQA/src/tokenizers/corenlp_tokenizer.py", line 61, in _launch
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fc2939ace10>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b'0:/OpenQA# bash: java: command not found\r\n\x1b]0;root@392696d4bc50: /OpenQA\x07root@392696d4bc50:/OpenQA# '
before (last 100 chars): b'0:/OpenQA# bash: java: command not found\r\n\x1b]0;root@392696d4bc50: /OpenQA\x07root@392696d4bc50:/OpenQA# '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 533
child_fd: 7
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"

**Comment by impulsecorp** [comment]
I am getting the same error. What was the solution?

**Comment by ruizewang** [comment]
The same question
